name: Create Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag alpine-dev:aarch64
        docker save alpine-dev:aarch64 >alpine-dev:aarch64
    - uses: actions/upload-artifact@v4
      with:
        name: alpine-dev.aarch64
        path: alpine-dev:aarch64
